### ISSUE TITLE
请问编辑节点问题内容时的阴影样式有办法调整

### ISSUE THREAD

**Issue by wjw020206** [wanglin2/mind-map#935]
如下图，这块周围的阴影样式可以调整吗？
![image](https://github.com/user-attachments/assets/f588b2b6-d647-4fbd-8e3b-2a4f5bfb0aa5)

**Comment by wanglin2** [comment]
自己css样式直接覆盖即可。

**Comment by wjw020206** [comment]
> 自己css样式直接覆盖即可。

感谢你的回复，我尝试如下 CSS 覆盖会影响我的富文本页面，因为富文本页面元素也包含 `contenteditable='true'` 属性，好像这个元素没有类名，我只能通过全局的方式进行覆盖

```css
/* 新脑图输入框的阴影配置 */
div[contenteditable='true'] {
  box-shadow: rgba(0, 0, 0, 0.1) 0px 0px 20px !important;
}
```
