### ISSUE TITLE
富文本模式下，如果容器元素，或更上层元素显式设置了字号，且文本编辑框和容器元素不在同一层，会导致节点显示和编辑时行高不一致的问题

### ISSUE THREAD

**Issue by wanglin2** [wanglin2/mind-map#948]

**Comment by wanglin2** [comment]
![image](https://github.com/user-attachments/assets/1a4b37fb-84d0-40a7-a9d1-81cc832a6678)
![image](https://github.com/user-attachments/assets/857cc50a-1114-4157-a6fc-0b9714900246)

**Comment by wanglin2** [comment]
节点文本明显偏下的原因一般是思维导图容器元素，或容器的任何一个祖先元素显式设置了`font-size`的样式，所以可以去除给容器元素或任何一个祖先元素设置的`font-size`样式，如果祖先元素因为一些原因无法去除，那么可以给容器元素添加如下样式：

```css
#mindMapContainer {
    font-size: initial;
}
```

至于编辑中的文本和显示文本不一致，是因为文本编辑框元素默认是插入到页面的`body`元素下，所以`font-size`没有影响到文本编辑元素，导致出现不一致，解决方法有两个：

1.给文本编辑框元素也设置同样的`font-size`样式：

```css
.smm-richtext-node-edit-wrap {
    font-size: 20px;
}
```

2.将文本编辑框元素插入到思维导图容器下，或其他可以受`font-size`样式影响的元素下：

```js
new MindMap({
    el: document.querySelector('#mindMapContainer'),
    customInnerElsAppendTo: document.querySelector('#mindMapContainer')
})
```
